# Generated by Django 5.0.6 on 2026-06-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Conversation title"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Question text")),
                (
                    "answer",
                    models.TextField(blank=True, verbose_name="Generated answer"),
                ),
                ("search_mode", models.CharField(default="hybrid", max_length=20)),
                (
                    "retrieved_chunks",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Retrieved chunks"
                    ),
                ),
                (
                    "sources",
                    models.JSONField(blank=True, null=True, verbose_name="Sources"),
                ),
                ("total_duration_sec", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="qa.conversation",
                        verbose_name="Conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question and Answer",
                "verbose_name_plural": "Question history",
                "ordering": ["-created_at"],
            },
        ),
    ]
