# Generated by Django 5.0.6 on 2026-06-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="DOCX file",
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True,
                        help_text="Automatically extracted from file",
                        verbose_name="Full text",
                    ),
                ),
                (
                    "is_indexed",
                    models.BooleanField(default=False, verbose_name="Indexed"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chunk_index",
                    models.PositiveIntegerField(verbose_name="Chunk number"),
                ),
                ("content", models.TextField(verbose_name="Chunk text")),
                (
                    "vector_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                        verbose_name="Document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document chunk",
                "verbose_name_plural": "Document chunks",
                "ordering": ["document", "chunk_index"],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
